### ISSUE TITLE
Nativescript Slider

### ISSUE THREAD

**Issue by shivapersad** [jlooper/nativescript-snacks#15]
Hi,

Could you do a tutorial on creating a Nativescript Slider in XML and capturing its value in Typescript? Also if possible to display the value of the Slider as you move it would be great. Thanks.

**Comment by bradmartin** [comment]
I'll work on this :+1: 
Snippet URL - fixed typo http://nativescript.it/3gz08c/3

**Comment by jlooper** [comment]
http://www.nativescriptsnacks.com/snippets/2016/08/03/slider.html
