### ISSUE TITLE
Some app with calculation

### ISSUE THREAD

**Issue by inakidb** [jlooper/nativescript-snacks#20]
I see is lack of examples in how to work with calculations, like a simple calculator or a split calc. Hope can make one.
Thanks Iñaki

**Comment by jlooper** [comment]
Perhaps this blogpost answers your needs? [https://www.nativescript.org/blog/details/calcunator-the-nativescript-calculator](https://www.nativescript.org/blog/details/calcunator-the-nativescript-calculator)

**Comment by jlooper** [comment]
@inakidb just stumbled on this one too, Bruno has a great blog : http://www.behaveonrails.com/?p=632
