### ISSUE TITLE
drag and drop between 2 listview

### ISSUE THREAD

**Issue by sflament** [jlooper/nativescript-snacks#28]
I would be very happy in viewing a tutorial showing how to perform drag and drop items between two listtview on the same screen.
I did not succeed, nor with Pan Gesture and classic Listview, nor with RadListview.

Stephane

**Comment by jlooper** [comment]
we do now have a drag/drop snippet (actually 2) - in case that might help?

**Comment by fourctv** [comment]
@jlooper I am also interested on a d&d tutorial. the existing snippets deal with moving around images.

what we are asking here is the ability to drag a row from one ListView and drop it into another, or to rearrange rows on a ListView

**Comment by jlooper** [comment]
Hi, take a look at the NativeScript-UI plugin. It has just that functionality as I remember.

**Comment by sflament** [comment]
Hello Jen, to rearrange items into one list is possible with radlistview feature. But i still waiting for a solution for moving items between two list in a same page.

**Comment by jlooper** [comment]
Oh! Fancy! I will look into it

**Comment by fourctv** [comment]
Yeah, after I wrote my comment I realized that RadListView has the reorder feature already. What we are missing is a way to drag & drop between ListViews or RadListViews.

**Comment by sflament** [comment]
Hello Jen, 
I still wait for a tutorial showing how to deal with a D&D between listviews or radlistviews, have you heard of something ?

Better if with Typescript and angular.
I'm not tough enough to succeed in this by myself.

**Comment by jlooper** [comment]
hi, I'm not either :D - let me raise this within our community, maybe someone could do something in Playground! Stay tuned!

**Comment by shiv19** [comment]
Here's one way to drag and drop in {N}
https://play.nativescript.org/?template=play-js&id=HLY5Uh

**Comment by jlooper** [comment]
Thanks @shiv19 ! added to latest snack playground page!

**Comment by sflament** [comment]
Thanks @jlooper and @shiv19 ! You give us a good starting point.

**Comment by snq** [comment]
The playground doesn't work for me :(

**Comment by phatakrajan** [comment]
@shiv19 @jlooper looks like the code in home-page.xml has been replaced with some default template. Can you please add sample code back?

**Comment by shiv19** [comment]
@phatakrajan add &v=1 to the end of the link
